### ISSUE TITLE
2 minute delay on every alert?

### ISSUE THREAD

**Issue by jimsy3** [Dom2364/PlaneAlerter#10]
there is some really big delay on every alert, so is there a way to make it like 5 seconds max or smth...
because recently i just checked that 1 plane was already saved in the daily report db @14:37:40 or smth, but the app+windows alert was only shown at 14:40:xx etc...
so it basically only alerts when the plane is already long gone or smth...

**Comment by Dom2364** [comment]
At the moment the program waits until the next check before sending an alert. I'm honestly not sure exactly why I made it like that but it's probably to make sure the aircraft is on radar for a while and not just something random. For long check intervals like 5 minutes, every alert will be delayed by 5 minutes. Without that wait for the next check, alerts should be sent within seconds of each check. I'll look into either removing the wait or making it optional in the settings in the next update.

**Comment by MikeJaworski** [comment]
This is also of interest to me because the geographical range of the alert I have set up is very small, so I otherwise need to hammer the VRS server with frequent requests lest I miss fast-moving aircraft that pass in and out of the area of interest in less than 2 check intervals...

**Comment by jimsy3** [comment]
when could be the next update with the huge delay fixed? j:

**Comment by Dom2364** [comment]
Probably in the next few weeks, been quite busy with work and other projects recently but I'll start working on PlaneAlerter again in the next few days. If you'd like to keep track of what I'm up to there's a public Trello board: https://trello.com/b/LT6Z8tPy/planealerter

**Comment by jimsy3** [comment]
ok cool, but another issue probably is that it randomly keeps giving alerts on entries that have "ignore condition" option ticked...

**Comment by Dom2364** [comment]
Not sure what you mean, if you're talking about the 'ignore following conditions' option for conditions, that will still allow alerts for that condition, but should prevent alerts of the same aircraft from multiple conditions.

For the new update, the delay has been removed so alerts will now be sent immediately after an aircraft matches a condition. It's mostly done but there's still one bug I'm trying to fix.

**Comment by jimsy3** [comment]
edit**
ok nice, but i guess i just didnt find the "disable" menu at the right time and just mixed it up with the 'ignore' option... which i'm still not sure of what it actually does then...

**Comment by Dom2364** [comment]
The 'ignore following conditions' option prevents later conditions from triggering. The way the program works is for each aircraft it will go through all of the conditions in the order they appear in the editor. If one of those conditions triggers an alert and has the ignore following conditions option enabled it will skip the rest of the conditions. If you expect multiple conditions to trigger together this avoids multiple alerts for one aircraft.

**Comment by jimsy3** [comment]
ah ok.... maybe you could replace some of the words of it to make it as "ignore next entries" or smth, because at the moment it sounds like it would have to ignore the conditions that are going to follow below the text in there....

**Comment by Dom2364** [comment]
Resolved in version 2.3.0
