### ISSUE TITLE
callsign alert too?

### ISSUE THREAD

**Issue by jimsy3** [Dom2364/PlaneAlerter#14]
at the moment it only shows the icao code in the alertEr* window, but would it be possible to format it into showing: callsign-icao (or icao-callsign)
otherwise it gets too crowded and everything gets lost into the "added" and "removed" texts etc...

**Comment by Dom2364** [comment]
I could add a format setting to the program settings, then you could specify [call]-[icao] or anything like [reg]-[call] ([type]) and it would show those properties instead of the icao in the log. Or I can just change it to callsign-icao.

**Comment by jimsy3** [comment]
callsign-icao would be good i guess

**Comment by jimsy3** [comment]
or maybe callsign---icao, because callsign also has 1 - in it...

**Comment by jimsy3** [comment]
there is also an issue, where i have changed the windows notification sound to my own custom .wav in the win/sounds folder, but it randomly just stops working (only the windows note appears, but no sound alert with it), so i dont know if this is an app issue or somekind of windows issue...

**Comment by Dom2364** [comment]
The app plays the Windows exclamation sound, whatever that is set to. Likely a Windows problem, but you can try enabling/disabling the notifications and sound alerts in PlaneAlerter to see if something is causing a conflict.

**Comment by jimsy3** [comment]
can the "callsign---icao" tweak be added to it?
and would it also be possible to make the alert window pop-up on top of other windows when there is a new event? or just make it blink in the taskbar or smth...
that would probably fix the weird sound bug also a bit - which probably even comes from a 'remote desktop' app that keeps muting all system sounds for some unknown or weird reason....

**Comment by Dom2364** [comment]
I don't quite understand what you're asking with the callsign---icao tweak, do you mean changing the format of messages in the main window log to something like '10:11:58 | ADDED      | 7C26B2---HXG | Condition Name'? I'll add an option to flash the taskbar, I feel like bringing the window to the front might get too annoying for some people

**Comment by jimsy3** [comment]
yes, if the plane's registration is A-SDXX and icao is 3C7000, then the alert should say:
"11:20:02 | ADDED | 3C7000---A-SDXX | alert description" etc... - because then its much easier to filter them if lots of alerts come at the same time and they all also write the "Lost Signal" and "Removed" text etc.
or maybe "3C7000 --- A-SDXX" if that is possible (with 2 spaces).

taskbar flash will be very useful too
