### ISSUE TITLE
Alerts are not stored at log

### ISSUE THREAD

**Issue by CzechCougar** [Dom2364/PlaneAlerter#18]
Even if alerts are triggered, there aren't stored at alerts.log

If I go via Options > Open log file I'll get this error

System.ComponentModel.Win32Exception (193): An error occurred trying to start process 'alerts.log' with working directory 'C:\Tools\Plane alerter\LETPC'. The specified executable is not a valid application for this OS platform.

I'm using Win 11 64-bit.

**Comment by jimsy3** [comment]
same error in win10, but dunno if it even shows something other than the red error in the console

**Comment by Dom2364** [comment]
Discovered there is a breaking change in the update to .NET 7 that causes this error when opening files, I'll change the open log file button to show the file in file explorer instead. The logs do seem to be writing for me, let me know if it isn't writing to alerts.log anymore for you

**Comment by CzechCougar** [comment]
After restarting the computer start storing alerts in the file ;)

**Comment by Dom2364** [comment]
Fixed in [2.5.1](https://github.com/Dom2364/PlaneAlerter/releases/tag/2.5.1)
