### ISSUE TITLE
Special charactes at URL

### ISSUE THREAD

**Issue by CzechCougar** [Dom2364/PlaneAlerter#19]
I'm using the port in my URL "http://127.0.0.1:85/VirtualRadar/aircraftList.json" and I'm getting an error: 

ERROR: Newtonsoft.Json.JsonReaderException while downloading AircraftList.json: Unexpected character encountered while parsing value: . Path '', line 0, position 0.

**Comment by jimsy3** [comment]
i have the same, win10

**Comment by Dom2364** [comment]
Just tested this on my PC (Windows 10, VRS 3.0.0 beta preview 10) running VRS on port 85 and it's sending alerts fine. The error seems to indicate Planealerter is receiving something from that port but it's not in the correct format. Are you able to open that aircraftList.json url in your browser and reply with the contents of it or save as a file and attach it? What version of VRS are you using as well?

**Comment by jimsy3** [comment]
i have the regular 244, 2019
`{"src":1,"feeds":[{"id":1,"name":"xxx1","polarPlot":false}],"srcFeed":1,"showSil":false,"showFlg":false,"showPic":false,"flgH":20,"flgW":85,"acList":[],"totalAc":0,"lastDv":"-1","shtTrlSec":30,"stm":16..xx..xxx....}`

**Comment by CzechCougar** [comment]
me to regular 2.4.4.36598
[aircraftList.zip](https://github.com/Dom2364/PlaneAlerter/files/11547366/aircraftList.zip)

I have had port 85 ever, and your previous version works fine.

**Comment by Dom2364** [comment]
Thanks for the info, just installed 2.4.4 and I'm now getting the same error. I found that the new HttpClient setup that I added wasn't done correctly so the aircraftList.json response was coming through as GZIP compressed data instead of JSON. I did test with VRS 3.0.0 and compression enabled in the web site settings so maybe the responses aren't compressed anymore in 3.0.0.

**Comment by Dom2364** [comment]
Fixed in [2.5.1](https://github.com/Dom2364/PlaneAlerter/releases/tag/2.5.1)
