### ISSUE TITLE
not flashing in the bottom?

### ISSUE THREAD

**Issue by jimsy3** [Dom2364/PlaneAlerter#20]
does the new version even flash in the bottom at all or is there a time limit when its doing it?  i thought its going to at least change color and blink in the bottom, but at the moment it's not doing any of that

**Comment by Dom2364** [comment]
Have you got the 'flash window' setting enabled in the settings? It also only flashes if the window is in the background and not selected.

**Comment by jimsy3** [comment]
ok thanks, i didnt know that there is a separate option for this, and it seems to be blinking now
