### ISSUE TITLE
Twitter 

### ISSUE THREAD

**Issue by Phalanx1010** [Dom2364/PlaneAlerter#24]
Where do I enter the key and token?

ERROR: Error publishing tweet: When authenticating requests to the Twitter API v2 endpoints, you must use keys and tokens from a Twitter developer App that is attached to a Project. You can create a project via the developer portal.
Reason : Forbidden
Code : 403
Date : 11/04/2023 12:03:08 +09:00
URL : https://api.twitter.com/2/tweets
Twitter documentation description : Forbidden - The request is understood, but it has been refused or access is not allowed. An accompanying error message will explain why. This code is used when requests are being denied due to update limits.

**Comment by Dom2364** [comment]
I just logged into the Twitter developer portal and the app was somehow removed from the project, I've just added it back so it should fix this
