### ISSUE TITLE
constant crash to desktop after adding new item to conditional editor

### ISSUE THREAD

**Issue by pilotadsb** [Dom2364/PlaneAlerter#25]
Hi,
I get constant crashes to desktop when adding an additional item with the condition editor to PlaneAlerter.
Is there a limit to total number of active or inactive condition in the list? I have about 96 in my list some are inactive and some are active. It seems like when I added past 92 is when these crashes started. At this point the planealerter in is non-functional and have tried it on 3 Windows 10 PC's. Is there an error log to debug? 

Not sure if this helps but here is the windows 10 internal fault log

Thanks

Description
Faulting Application Path:	C:\radio\Planealerter-252-64\PlaneAlerter.exe

Problem signature
Problem Event Name:	APPCRASH
Application Name:	PlaneAlerter.exe
Application Version:	2.5.2.0
Application Timestamp:	638f99ee
Fault Module Name:	KERNELBASE.dll
Fault Module Version:	10.0.19041.4291
Fault Module Timestamp:	a956ff71
Exception Code:	e0434352
Exception Offset:	000000000002ab89
OS Version:	10.0.19045.2.0.0.256.48
Locale ID:	1033
Additional Information 1:	4b11
Additional Information 2:	4b11b578910323ba1481d2d8d0440474
Additional Information 3:	d189
Additional Information 4:	d1899de36138d348423ea67764fc5ef3

Extra information about the problem
Bucket ID:	3f79d80036e1d85bb56e826d134e30b6 (1544315127221596342)

**Comment by Dom2364** [comment]
Hey, in the Windows Event Viewer there should be some useful error info in the logs with a Source of '.NET Runtime'. Can you also send your conditions.json to me at dom@dominichubert.com.au?

**Comment by pilotadsb** [comment]
Thanks I did look at the event viewer logs but since I am not a programmer
did not understand it.

Do you want me to zip and email it to you?

Thanks
John

**Comment by Dom2364** [comment]
Sure that would be great thanks

**Comment by pilotadsb** [comment]
did you get my windows logs? I sent them as .txt files by reply to your last email or do they need to be attached through this web tool? 
John

**Comment by pilotadsb** [comment]
[net runtime error.txt](https://github.com/Dom2364/PlaneAlerter/files/15278693/net.runtime.error.txt)
[planealerter application  @error.txt](https://github.com/Dom2364/PlaneAlerter/files/15278694/planealerter.application.error.txt)
@

**Comment by Dom2364** [comment]
That runtime error is what I'm after, not sure how that's happening though so I'll need to spend a while trying to recreate it myself

**Comment by pilotadsb** [comment]
Thanks no problem so you got the files OK

John

**Comment by Dom2364** [comment]
I think I found the problem, should be fixed now. I'll release an update hopefully in the next week or two, depends how busy I get with other things.

**Comment by pilotadsb** [comment]
Awesome great thanks for the update. Just curious as to what the problem
was? Is it a configuration type problem or the number of conditions?

Thanks
John

**Comment by pilotadsb** [comment]
One question I’m not sure if it’s been asked before, but I searched and
couldn’t find the answer.

Is there a simple way to copy all of my saved conditions to a new version
of plane alerter without having to manually enter them all over again?

I have about 95 conditions / rules setup in planealerter and woul be nice
to just copy or backup the data file. Would just copy the conditions file
work?

John

**Comment by Dom2364** [comment]
The problem was that there were likely multiple checks happening at the same time, and the internal aircraft list that PlaneAlerter manages was being changed while it was in use by another part of the program. Not sure if the number of conditions relates to that and I couldn't replicate the exact error but that's the most likely cause. Now it should be impossible for two checks to happen at the same time so that could solve many various issues.

You can copy the conditions.json to the new version, each new version should support old versions unless stated in the changelog.

**Comment by Dom2364** [comment]
Just released [2.6.0](https://github.com/Dom2364/PlaneAlerter/releases/tag/2.6.0) which should hopefully fix this, let me know if it does and I'll close the issue

**Comment by jimsy3** [comment]
it probably does not work with .net 9.0 now? asks for 7.0 or smth and quits

**Comment by jimsy3** [comment]
?

**Comment by pilotadsb** [comment]
Having an upgraded to 9.0 so haven’t tried it with that version
Very happy with the work you did on the last build working great appreciate
that update to fix it

**Comment by pilotadsb** [comment]
Have not upgraded to 9.0 yet sorry for the typing error.
Works great with the last update you did very pleased so not in a hurry to
upgrade right now to net 9.0
