### ISSUE TITLE
Twitter add account problem

### ISSUE THREAD

**Issue by PhilipG0ISW** [Dom2364/PlaneAlerter#6]
Hi Dom,

Trying to add a Twitter account fails with 'Tweetinvi. AuthFlow' threw an exception.

Looking at the details it appears it could not load 'AutoFac' and 'manifest definition does not match  the assembly reference'

I see on the VRS forum others with the same error

Regards

Philip

**Comment by Dom2364** [comment]
Resolved in [2.1.3](https://github.com/Dom2364/PlaneAlerter/releases/tag/2.1.3)
