### ISSUE TITLE
only sound plz

### ISSUE THREAD

**Issue by jimsy3** [Dom2364/PlaneAlerter#8]
can i use it as a sound alert only without any email or twitter messages?

**Comment by Dom2364** [comment]
You can't at the moment, but I've just changed it so in the next update you will be able to have conditions without email or twitter alerts.

**Comment by jimsy3** [comment]
PS: the the alert should sound on every plane detection also, not only on some predefined filter letters or smth... thanks.

**Comment by jimsy3** [comment]
oops sorry, dont even know what the last post was meant to mean lol...

**Comment by jimsy3** [comment]
well... maybe just a small beep for every plane that goes by? and then a different alert sound for your own alerts...
